# Generated by Django 5.1.5 on 2025-02-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventPlanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(default='photos/no.jpg', upload_to='photos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(default='photos/no.jpg', upload_to='photos'),
            preserve_default=False,
        ),
    ]
