# Generated by Django 5.1.5 on 2025-02-02 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventPlanner', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
